FROM tensorflow/tensorflow:latest

WORKDIR /app

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 -y

RUN pip install --no-cache-dir fastapi uvicorn Pillow opencv-python python-multipart

COPY . .

EXPOSE 8000

CMD python app.py